/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Bidirectional handle to a running exec: write stdin, read events via `next()`. */
export declare class ExecHandle {
  write(data: Buffer): Promise<void>
  eof(): Promise<void>
  signal(sig: number): Promise<void>
  resize(cols: number, rows: number): Promise<void>
  /** The next event, or `null` when the exec stream ends. */
  next(): Promise<ExecEventJs | null>
}

/** A connection to a Chevalier sandbox provider. */
export declare class Sandbox {
  /** Connect to a sandbox provider. */
  static connect(endpoint: string, options?: SandboxConnectOptions | undefined | null): Promise<Sandbox>
  /** Create a new session (microVM). */
  session(options?: SessionOpts | undefined | null): Promise<Session>
  /** Attach to an existing session by id. */
  attachSession(sessionId: string): Promise<Session>
  /** List live sessions visible to this sandbox provider. */
  listSessions(): Promise<Array<SessionInfoJs>>
  /** Discard a provider session by id, even if this process does not hold a Session handle. */
  discardSessionById(sessionId: string): Promise<void>
}

/** A sandbox session (one microVM). */
export declare class Session {
  get sessionId(): string
  get vmId(): string
  /** Start a command; returns a bidirectional `ExecHandle`. */
  exec(command: string, options?: ExecOpts | undefined | null): Promise<ExecHandle>
  /** Read a file from the guest. */
  readFile(path: string): Promise<Buffer>
  /** Write a file to the guest. */
  writeFile(path: string, data: Buffer): Promise<void>
  /** Fork this session (CoW); returns the child session. */
  fork(options?: ForkOpts | undefined | null): Promise<Session>
  /** Create a checkpoint/snapshot for this session. */
  checkpoint(name: string): Promise<SessionCheckpointJs>
  /** Restore a checkpoint into a new session. */
  restoreCheckpoint(checkpointId: string): Promise<Session>
  /** Read the current VM state from the sandbox provider. */
  getState(): Promise<string>
  /** Pause the VM without deleting it. */
  pause(): Promise<string>
  /** Resume a paused VM. */
  resume(): Promise<string>
  /** Stop the VM without deleting its record. */
  stop(): Promise<string>
  /** Create a VM snapshot/checkpoint. */
  snapshot(options?: SessionSnapshotOpts | undefined | null): Promise<SessionSnapshotJs>
  /** Restore this VM from a snapshot. */
  restore(snapshotId: string): Promise<string>
  /** List snapshots for this VM. */
  listSnapshots(): Promise<Array<SessionSnapshotJs>>
  /** Delete a VM snapshot. */
  deleteSnapshot(snapshotId: string): Promise<void>
  /** Close the session handle without deleting the VM. */
  close(): Promise<void>
  /** Delete the backing VM/sandbox and purge provider resources. */
  discard(): Promise<void>
}

/** A single exec event. `type` is `stdout` | `stderr` | `exit` | `timeout`. */
export interface ExecEventJs {
  type: string
  data?: Buffer
  code?: number
}

export interface ExecOpts {
  env?: Record<string, string>
  timeoutSecs?: number
  detach?: boolean
  shell?: string
  closeStdinOnStart?: boolean
}

export interface ForkOpts {
  childName?: string
  childMetadata?: Record<string, string>
  autoStartChild?: boolean
}

export interface OpenComputerMountOpts {
  path?: string
  driver?: string
  remote?: string
  backend?: string
  command?: Array<string>
  env?: Record<string, string>
  secrets?: Record<string, string>
  creds?: Record<string, string>
  rcloneConfig?: string
  readOnly?: boolean
  mountOptions?: Array<string>
}

export interface OpenComputerProviderOpts {
  apiUrl?: string
  apiKey?: string
  templateId?: string
  timeoutSecs?: number
  defaultCpuCount?: number
  defaultMemoryMb?: number
  defaultDiskMb?: number
  burst?: boolean
  secretStore?: string
  egressAllowlist?: Array<string>
  mounts?: Array<OpenComputerMountOpts>
  sharedMounts?: Record<string, OpenComputerMountOpts>
}

export interface SandboxConnectOptions {
  authToken?: string
  connectTimeoutMs?: number
  defaultImage?: string
  provider?: string
  openComputer?: OpenComputerProviderOpts
}

export interface SessionCheckpointJs {
  id: string
}

export interface SessionInfoJs {
  sessionId: string
  vmId: string
  name: string
  state: number
  branchId?: string
  parentSessionId?: string
  forkId?: string
}

export interface SessionOpts {
  sessionId?: string
  name?: string
  image?: string
  architecture?: string
  metadata?: Record<string, string>
  autoStart?: boolean
  sharedMounts?: Array<SharedMountOpts>
  egressAllowlist?: Array<string>
}

export interface SessionSnapshotJs {
  id: string
  name: string
  label: string
  description: string
}

export interface SessionSnapshotOpts {
  label?: string
  description?: string
}

export interface SharedMountOpts {
  hostPath?: string
  guestPath: string
  mountTag: string
  readOnly?: boolean
  availability?: string
  continuity?: string
  backendProfile?: string
  vfsEndpoint?: string
  vfsScopePath?: string
}
