/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Bidirectional handle to a running exec: write stdin, read events via `next()`. */
export declare class ExecHandle {
  write(data: Buffer): Promise<void>
  eof(): Promise<void>
  signal(sig: number): Promise<void>
  resize(cols: number, rows: number): Promise<void>
  /** The next event, or `null` when the exec stream ends. */
  next(): Promise<ExecEventJs | null>
}

/** A connection to a `vmd` sandbox daemon. */
export declare class Sandbox {
  /** Connect to an external `vmd` at `endpoint` (e.g. `http://127.0.0.1:8052`). */
  static connect(endpoint: string, options?: SandboxConnectOptions | undefined | null): Promise<Sandbox>
  /** Create a new session (microVM). */
  session(options?: SessionOpts | undefined | null): Promise<Session>
  /** Attach to an existing session by id. */
  attachSession(sessionId: string): Promise<Session>
}

/** A sandbox session (one microVM). */
export declare class Session {
  get sessionId(): string
  get vmId(): string
  /** Start a command; returns a bidirectional `ExecHandle`. */
  exec(command: string, options?: ExecOpts | undefined | null): Promise<ExecHandle>
  /** Read a file from the guest. */
  readFile(path: string): Promise<Buffer>
  /** Write a file to the guest. */
  writeFile(path: string, data: Buffer): Promise<void>
  /** Fork this session (CoW); returns the child session. */
  fork(options?: ForkOpts | undefined | null): Promise<Session>
}

/** A single exec event. `type` is `stdout` | `stderr` | `exit` | `timeout`. */
export interface ExecEventJs {
  type: string
  data?: Buffer
  code?: number
}

export interface ExecOpts {
  env?: Record<string, string>
  timeoutSecs?: number
  detach?: boolean
  shell?: string
  closeStdinOnStart?: boolean
}

export interface ForkOpts {
  childName?: string
  childMetadata?: Record<string, string>
  autoStartChild?: boolean
}

export interface SandboxConnectOptions {
  authToken?: string
  connectTimeoutMs?: number
  defaultImage?: string
}

export interface SessionOpts {
  sessionId?: string
  name?: string
  image?: string
  architecture?: string
  metadata?: Record<string, string>
  autoStart?: boolean
}
