/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A connection to an MCP server. */
export declare class McpClient {
  /** Connect over streamable HTTP, e.g. `http://localhost:8080/mcp`. */
  static http(url: string): Promise<McpClient>
  /** Connect over WebSocket, e.g. `ws://localhost:8080`. */
  static websocket(url: string): Promise<McpClient>
  /**
   * Spawn a child process and connect over stdio, e.g.
   * `npx @modelcontextprotocol/server-filesystem /tmp`.
   */
  static stdio(commandLine: string): Promise<McpClient>
  /** List the server's tools (JSON). */
  listTools(): Promise<any>
  /** Call a tool with JSON arguments; returns the tool result (JSON). */
  callTool(name: string, args: any): Promise<any>
  /** List the server's resources (JSON). */
  listResources(): Promise<any>
  /** Read a resource by URI (JSON). */
  readResource(uri: string): Promise<any>
}

/** Build and serve an MCP server. Register tools, then `serve(...)`. */
export declare class McpServer {
  constructor(name: string, options?: McpServerOptions | undefined | null)
  /**
   * Register a tool. The handler receives the parsed JSON args and returns a
   * `Promise<string>` (wrapped as the tool's text result).
   */
  tool(name: string, description: string, schema: any, handler: (args: any) => Promise<string>): Promise<void>
  /**
   * Serve the registered tools. `transport` is `"stdio"`, `"http"`, or
   * `"websocket"`; `addr` (e.g. `127.0.0.1:8080`) is required for http/ws.
   * Resolves when the server stops.
   */
  serve(transport: string, addr?: string | undefined | null): Promise<void>
}

/** The Chevalier agent runtime. */
export declare class Runtime {
  constructor(options?: RuntimeOptions | undefined | null)
  /** Non-streaming inference call. */
  run(options: RunOptions): Promise<RunResult>
  /**
   * Register a tool backed by an async JS handler. The handler receives the
   * parsed JSON args and returns `Promise<string>`. The engine invokes it via
   * `executeToolCall` (the agent loop is consumer-driven).
   */
  tool(name: string, description: string, schema: any, handler: (args: any) => Promise<string>): Promise<void>
  /**
   * Register a tool by schema only (no handler) — the model can call it, and
   * the host dispatches it from the response/stream. Calling it via the engine
   * errors (there is no handler).
   */
  registerToolSchema(name: string, description: string, schema: any): Promise<void>
  /** Execute a registered (handler-backed) tool call and return its string result. */
  executeToolCall(toolName: string, args: any): Promise<string>
  /**
   * Streaming inference call. Returns a `StreamHandle`; pull events with
   * `next()` until it yields `null`.
   */
  runStream(options: RunOptions): Promise<StreamHandle>
  /** All registered tool schemas (name, description, JSON-schema parameters). */
  getToolSchemas(): Promise<Array<ToolSchemaJs>>
  /** Set a structured system-message prefix applied to subsequent runs. */
  setSystemMessages(messages: Array<Message>): Promise<void>
  /** Set the default prompt used when a run omits `prompt`. */
  setDefaultPrompt(prompt: string): Promise<void>
  /** Set provider-specific request shaping (e.g. Anthropic prompt caching). */
  setProviderConfig(config: ProviderConfigInput): Promise<void>
  /** Accumulated assistant text from the last run/stream. */
  rawResponse(): Promise<string>
  /** Accumulated reasoning text from the last run/stream. */
  reasoning(): Promise<string>
  /** Accumulated reasoning segments (JSON) from the last run/stream. */
  reasoningSegments(): Promise<any>
  /**
   * Connect to an MCP server and register all its tools onto this runtime.
   * Transport is auto-detected: `http(s)://` → HTTP, `ws(s)://` → WebSocket,
   * otherwise stdio (a command to spawn).
   */
  mcp(uri: string): Promise<void>
  /** Like `mcp`, but namespaces the registered tools as `{label}_{tool}`. */
  mcpAs(uri: string, label: string): Promise<void>
}

/**
 * Async cursor over a streaming run. Call `next()` until it returns `null`.
 * The TS layer wraps this with `Symbol.asyncIterator` for `for await`.
 */
export declare class StreamHandle {
  /**
   * The next event, or `null` when the stream is exhausted. Throws if the
   * underlying run errored.
   */
  next(): Promise<StreamEvent | null>
}

/**
 * A virtual filesystem. Construct via `VfsStorage.local(root)` or
 * `VfsStorage.gateway(opts)`.
 */
export declare class VfsStorage {
  /** Filesystem-backed storage rooted at `root`. */
  static local(root: string): VfsStorage
  /** HTTP gateway-backed storage. */
  static gateway(options: GatewayOptions): VfsStorage
  /** Read a file's bytes. */
  read(path: string): Promise<Buffer>
  /** Write a file; returns the write result (JSON: content hash, changed, …). */
  write(path: string, data: Buffer): Promise<any>
  /** Stat a path; returns metadata JSON or null. */
  stat(path: string): Promise<any | null>
  /** List a directory's entries with metadata (JSON array). */
  listDir(path: string): Promise<Array<any>>
  /** Create a directory. */
  mkdir(path: string): Promise<void>
  /** Delete a file; returns the delete result (JSON). */
  remove(path: string): Promise<any>
  /** Remove an (empty) directory. */
  rmdir(path: string): Promise<void>
  /** Rename/move a file; returns the rename result (JSON). */
  rename(from: string, to: string): Promise<any>
}

/** Anthropic prompt-caching config. Cache markers are `"ephemeral"` or `"ephemeral1h"`. */
export interface AnthropicCacheConfig {
  automaticPromptCaching?: string
  toolDefinitionsCacheBreakpoint?: string
}

/** Options for the HTTP gateway backend. */
export interface GatewayOptions {
  endpoint: string
  authToken?: string
  scopePath?: string
  component?: string
  mutationReason?: string
}

/** Options for constructing an `McpServer`. */
export interface McpServerOptions {
  version?: string
  description?: string
}

/** A part of a multimodal message. `type` is `text` or `image`. */
export interface MediaPartInput {
  type: string
  text?: string
  imageBase64?: string
  mimeType?: string
  imageUrl?: string
}

/**
 * A conversation message. `type` selects the variant:
 * - `chat` → `{ role: "user"|"assistant"|"system", content }`
 * - `toolResult` → `{ toolUseId, content, isError?, toolName? }`
 * - `reasoning` → `{ content }`
 * - `multimodal` → `{ parts: [{ type:"text", text } | { type:"image", imageBase64, mimeType }] }`
 */
export interface Message {
  type: string
  role?: string
  content?: string
  toolUseId?: string
  toolName?: string
  isError?: boolean
  parts?: Array<MediaPartInput>
}

/** Provider-specific request shaping. */
export interface ProviderConfigInput {
  anthropic?: AnthropicCacheConfig
}

/** Options for a single `run` / `runStream` call. */
export interface RunOptions {
  prompt?: string
  system?: string
  temperature?: number
  topP?: number
  maxTokens?: number
  /** Override the runtime's model for this call. */
  model?: string
  /** Override the runtime's API key for this call. */
  apiKey?: string
  /** JSON Schema for structured output (the TS layer derives this from Zod). */
  outputSchema?: any
  /** Name/title for the output type (optional hint for the provider). */
  outputType?: string
  /** Prior conversation turns (chat / toolResult / reasoning). */
  history?: Array<Message>
  /** Per-call timeout in milliseconds. */
  timeoutMs?: number
}

/** Result of a non-streaming `Runtime.run`. */
export interface RunResult {
  /**
   * Concatenated assistant text (for structured output this is the JSON
   * string to decode against your schema).
   */
  text: string
  /** Concatenated extended-thinking / reasoning text, if any. */
  reasoning: string
  /** Tool calls the model requested. */
  toolCalls: Array<ToolCallJs>
  /** Provider reasoning signatures, if any. */
  signatures: Array<string>
}

/** Options for constructing a `Runtime`. */
export interface RuntimeOptions {
  /**
   * Provider model string, e.g. `anthropic:claude-3-5-sonnet` or
   * `openai:gpt-4o@server_url=http://host:port/v1`.
   */
  model?: string
  /** API key. Falls back to the provider's env var when omitted. */
  apiKey?: string
}

/**
 * A single streamed event. Discriminated by `type`:
 * `content` | `reasoning` | `signature` | `toolCall` | `toolPartial` | `usage` | `complete`.
 */
export interface StreamEvent {
  type: string
  /** Present for `content` / `reasoning` / `signature`. */
  text?: string
  /** Present for `toolCall`. */
  toolCall?: ToolCallJs
  /** Raw payload for `toolPartial` (partial args), `usage`, `complete` (full response). */
  data?: any
}

/** A tool call emitted by the model. */
export interface ToolCallJs {
  toolUseId: string
  toolName: string
  /** Parsed arguments (JSON object). */
  args: any
}

/** Registered tool schema (for introspection / sending to a provider). */
export interface ToolSchemaJs {
  name: string
  description: string
  /** JSON Schema for the tool's parameters. */
  parameters: any
}

/** The chevalier-node binding version. */
export declare function version(): string
